const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const clarityTag = `<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "yspilqirp9");
</script>`;
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const ordinyUrl='https://salon-platform-web-staging.pages.dev/';
const cashUrl='https://www.behance.net/gallery/192799873/Cash-Advance-Estudo-de-caso-UX-UI-Design';
const lumenUrl='https://www.behance.net/gallery/234488301/Lumen-simulador-de-consumo-de-energia';
const aquiUrl='https://www.behance.net/gallery/234762579/Landing-Page-Aqui-Limpa';
const external='target="_blank" rel="noopener noreferrer"';
const link=(href,label,style='button')=>`<a class="${style}" href="${esc(href)}" ${href.startsWith('https:')?external:''}>${label}</a>`;
const figure=(name,width,height,title)=>`<iframe class="native-art" src="assets/art/${name}.html" title="${esc(title)}" tabindex="-1" loading="lazy" style="aspect-ratio:${width}/${height}"></iframe>`;
const heading=(label,title,body='')=>`<div class="section-heading reveal"><p class="eyebrow">${label}</p><h2>${title}</h2>${body?`<p>${body}</p>`:''}</div>`;
const section=(id,theme,body)=>`<section ${id?`id="${id}"`:''} class="section case-section ${theme}"><div class="container stack">${body}</div></section>`;
const info=(title,body)=>`<article class="info-block reveal"><h3>${title}</h3><p>${body}</p></article>`;
const decision=(label,title,challenge,choice,care)=>`<article class="case-decision reveal"><p class="eyebrow accent">${label}</p><h3>${title}</h3>${[['DESAFIO',challenge],['ESCOLHA',choice],['CUIDADO DE PRODUTO',care]].map(([label,body])=>`<div><p class="mono">${label}</p><p>${body}</p></div>`).join('')}</article>`;
function page(file,title,description,body){
  const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101114"><title>${esc(title)}: Fabiano Antero</title><meta name="description" content="${esc(description)}"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/language.css"><link rel="stylesheet" href="assets/css/chibi-pet.css">${file==='projetos.html'?'<link rel="stylesheet" href="assets/css/collection.css">':''}${file==='cash-advance.html'?'<link rel="stylesheet" href="assets/css/cash-case.css">':''}<script src="assets/js/i18n.js" defer></script><script src="assets/js/app.js" defer></script><script type="module" src="assets/js/chibi-pet.js"></script></head><body${file==='cash-advance.html'?' class="cash-page"':''}><a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="site-header case-header"><div class="container header-inner"><a class="brand" href="index.html">FABIANO ANTERO</a><nav aria-label="Navegação principal"><a href="index.html">Home</a><a href="projetos.html" ${file==='projetos.html'?'aria-current="page"':''}>Projetos</a></nav><div class="language mono" role="group" aria-label="Idioma da página"><button type="button" data-language="pt" lang="pt-BR" aria-pressed="true">PT</button><span aria-hidden="true">/</span><button type="button" data-language="en" lang="en" aria-pressed="false">ENG</button></div></div></header><main id="conteudo">${body}</main><footer class="site-footer"><div class="container"><p class="mono">FABIANO ANTERO / PORTFÓLIO 2026</p><div class="footer-actions">${link('projetos.html','Todos os projetos ↗','text-link')}</div></div></footer></body></html>`;
  fs.writeFileSync(path.join(root,file),html.replace('</head>',`${clarityTag}</head>`));
}
const projects=[
  {title:'Ordiny',category:'SAAS / PRODUTO DIGITAL',summary:'Do design à aplicação: um SaaS que conecta produto, UX/UI e desenvolvimento.',role:'Produto · UX/UI · Desenvolvimento',href:'ordiny.html',src:'d2-imgImagemDoProjeto.png',alt:'Ordiny: interfaces da agenda e da gestão de atendimentos',cover:'ordiny',width:1440,height:1080},
  {title:'Cash Advance',category:'FINTECH / APLICATIVO',summary:'Antecipação de fretes com foco em clareza e segurança na jornada financeira.',role:'UX/UI · Jornada financeira',href:'cash-advance.html',cash:true},
  {title:'Lumen',category:'UTILITIES / SIMULADOR',summary:'Uma interface para explorar e compreender o consumo de energia.',role:'UX/UI · Visualização de informação',href:lumenUrl,src:'d2-imgImagemDoProjeto1.png',alt:'Telas do simulador de consumo de energia Lumen',cover:'lumen',width:843,height:632},
  {title:'Aqui Limpa',category:'SERVIÇOS / WEBSITE',summary:'Um site que apresenta serviços de limpeza com informações claras e uma navegação organizada.',role:'UI · Hierarquia de conteúdo',href:aquiUrl,src:'d2-imgImagemDoProjeto2.png',alt:'Site Aqui Limpa, apresentação de serviços de limpeza',cover:'aqui',width:1971,height:1972}
];
page('projetos.html','Projetos','Explore os trabalhos de Fabiano Antero em finanças, serviços e consumo de energia.',section('','',`<div class="collection-hero reveal"><p class="eyebrow accent">PORTFÓLIO / 04 PROJETOS</p><h1>Projetos,<br> por dentro.</h1><p>Produtos, interfaces e experiências em finanças, serviços e consumo de energia.</p></div>`)+section('','paper',`<h3 class="reveal">Explore os trabalhos</h3><div class="project-grid collection-grid">${projects.map(project=>`<article class="project-card reveal">${project.cash?`<a class="cash-cover collection-cover collection-cover-cash image-link" href="${project.href}" aria-label="Ver Cash Advance"><div class="cash-icon"><img src="assets/figma/d0-imgCurrencyDollar.svg" alt="" width="24" height="24"></div><div class="cash-cover-copy"><strong>CASH<br> ADVANCE</strong><p>Antecipar é simples.<br> Dar segurança antes do clique<br> é o desafio.</p></div><div class="cash-device"><img src="assets/img/smart-cash-hd.png" width="365" height="893" alt="Home financeira Cash Advance" loading="lazy"></div></a>`:`<a class="project-cover collection-cover collection-cover-${project.cover} image-link" href="${project.href}" ${project.href.startsWith('https:')?external:''}><img src="assets/figma/${project.src}" alt="${project.alt}" width="${project.width}" height="${project.height}" loading="lazy"></a>`}<div class="project-summary"><p class="mono">${project.category}</p><h3>${project.title}</h3><p>${project.summary}</p><p class="label">${project.role}</p>${link(project.href,project.href.startsWith('https:')?'Ver projeto ↗':'Ler estudo de caso ↗','text-link')}</div></article>`).join('')}</div>`)+section('','contact',heading('','Tem outro desafio em mente?','Vamos conversar sobre produto, design e implementação.')+link('index.html#contato','Vamos conversar ↗','button button-dark')));
const chapters=['Contexto','Jornada','Operação','Reserva','Pagamentos','Conversas','Construção','Entrega'];
const chapterIds=['contexto','jornada','operacao','reserva','pagamentos','conversas','construcao','entrega'];
const ordinyIntro=section('','',`<div class="case-opening reveal">${link('projetos.html','← Todos os projetos','text-link')}<p class="eyebrow accent">PROJETO PESSOAL / SAAS / EM DESENVOLVIMENTO</p><h1>Ordiny.<br> <span class="accent">Da captação à gestão<br> do atendimento.</span></h1><p>Projetei e desenvolvi um SaaS que conecta o agendamento do cliente à rotina do estabelecimento. Da escolha do serviço ao atendimento, as etapas compartilham as mesmas regras.</p>${link(ordinyUrl,'Abrir a Ordiny ↗')}<nav class="chapter-nav" aria-label="Capítulos do estudo Ordiny">${chapters.map((name,i)=>link('#'+chapterIds[i],`0${i+1} ${name}`,'chapter-link')).join('')}</nav></div>`);
const ordinyProduct=`<section class="paper"><div class="product-art reveal">${figure('ordiny-product',1440,868,'Composição do produto Ordiny: agenda, conversa de confirmação e painel de gestão')}</div><div class="container product-facts three-columns">${[['CONTEXTO','Serviços agendados','Estabelecimentos, profissionais e clientes finais.'],['MEU PAPEL','Produto, design e código','UX/UI, front-end, back-end, arquitetura e infraestrutura.'],['ENTREGA','Jornada conectada','Da captação à reserva, ao atendimento e ao relacionamento.']].map(([label,title,body])=>`<article class="reveal"><p class="mono">${label}</p><h3>${title}</h3><p>${body}</p></article>`).join('')}</div></section>`;
const ordinyContext=section('contexto','paper',heading('01 / CONTEXTO','O problema era a ruptura entre etapas.','Conversas precisavam ser registradas manualmente, reagendamentos exigiam novas verificações de disponibilidade e pagamentos precisavam ser vinculados aos atendimentos. A continuidade dependia de trabalho manual.')+`<hr><div class="two-columns">${info('O que precisava mudar','Conectar reserva, atendimento e pagamento para reduzir registros repetidos e prevenir conflitos na agenda.')}${info('Dois públicos, uma operação','O cliente precisa encontrar e reservar o serviço. O estabelecimento precisa cumprir a reserva e acompanhar a operação, inclusive entre unidades.')}</div>`);
const ordinyJourney=section('jornada','',heading('02 / JORNADA','Cada etapa prepara a próxima.','A jornada conecta o agendamento feito pelo cliente à realização do atendimento pela unidade.')+`<div class="four-columns journey-grid">${[['01 / ENTRAR','Conhecer e começar','Site, planos, cadastro e confirmação por e-mail. Avaliação gratuita por 15 dias.'],['02 / PREPARAR','Preparar a unidade','A configuração dos serviços, dos profissionais e da disponibilidade define as opções do link público e das integrações.'],['03 / RESERVAR','Escolher e reservar','Link público ou WhatsApp. Serviço, profissional e horário validados na confirmação.'],['04 / ACOMPANHAR','Atender e acompanhar','A reserva entra na agenda, nas notificações e nos registros da operação.']].map(([label,title,body])=>`<article class="reveal"><p class="eyebrow accent">${label}</p><h3>${title}</h3><p>${body}</p></article>`).join('')}</div><div class="journey-summary reveal">A seleção do cliente precisa se transformar em um atendimento que a unidade consegue cumprir.</div><p class="mono">Mapa explicativo do produto; os fluxos abaixo aprofundam suas regras.</p>`);
const ordinyOperations=section('operacao','paper',heading('03 / OPERAÇÃO','Uma unidade, diferentes papéis.','Organizei a operação por responsabilidade: proprietário, recepção e profissionais. O cliente agenda pelos canais públicos.')+`<div class="operation-grid"><div class="stack reveal"><p class="mono">FRENTES DA OPERAÇÃO</p>${info('Agenda + equipe','Disponibilidade, status, reagendamentos e cancelamentos.')}${info('Clientes + catálogo','Contato, consentimento, serviços e pacotes.')}${info('Registros + configurações','Registros financeiros, regras, integrações e aparência.')}</div><figure class="comparison-figure reveal"><div class="comparison" aria-label="Comparação dos temas claro e escuro da Ordiny"><img class="comparison-light" src="assets/figma/o4-imgImage49.png" alt="Ordiny em tema claro, painel desktop e mobile" width="848" height="636" loading="lazy"><div class="comparison-sweep"><img src="assets/figma/o4-imgImage51.png" alt="Ordiny em tema escuro, painel desktop e mobile" width="848" height="636" loading="lazy"></div><div class="comparison-indicator" data-node-id="253:1434"><span aria-hidden="true">← │ →</span></div><input class="comparison-control" type="range" min="0" max="100" value="50" step="1" aria-label="Posição do divisor entre os temas claro e escuro" aria-describedby="comparison-instructions"></div><figcaption id="comparison-instructions">Arraste o divisor ou use as setas do teclado para comparar os temas.</figcaption></figure></div><div class="two-columns">${info('BackOffice da Ordiny','Ambiente separado para administrar clientes da plataforma, planos e ocorrências.')}${info('Permissão é uma regra do sistema','Perfis orientam as ações visíveis; a API verifica a permissão em cada operação.')}</div>`);
const ordinyBooking=section('reserva','',heading('04 / RESERVA','Uma vitrine que respeita a agenda.','A unidade prepara sua vitrine; o cliente escolhe serviços e pacotes e segue para a reserva. A personalização mantém a identidade de cada estabelecimento.')+`<p class="mono">DA CONFIGURAÇÃO DA UNIDADE À ESCOLHA DO CLIENTE</p><div class="three-columns booking-screens">${[['02 / PREPARAR A UNIDADE','o5-imgImage50.png','A unidade ativa o link e define a antecedência das reservas.','configure'],['03 / ENCONTRAR O SERVIÇO','o5-imgImage52.png','Identidade, serviços e pacotes ajudam o cliente a escolher.','catalog'],['04 / ESCOLHER O HORÁRIO','o5-imgImage51.png','Profissional, data e horário com o resumo da seleção. A reserva é revalidada ao confirmar.','booking']].map(([label,src,caption,kind])=>`<figure class="reveal"><p class="eyebrow accent">${label}</p><div class="ordiny-phone ${kind}"><img src="assets/figma/${src}" alt="${caption}" loading="lazy" width="624" height="837"></div><figcaption>${caption}</figcaption></figure>`).join('')}</div><p class="mono">TELAS DO PROJETO NO FIGMA / DADOS ILUSTRATIVOS</p><div class="decision-grid">${decision('DECISÃO / CONTINUIDADE','Confirmar com a disponibilidade atual.','Reservas com serviços e pacotes precisam considerar a duração total, o valor e os profissionais habilitados.','Painel, link público e WhatsApp usam as mesmas regras de disponibilidade. A reserva é revalidada na confirmação.','Um horário disponível pode ser reservado por outra pessoa antes da confirmação. A opção “Qualquer profissional” considera a habilitação para o serviço e a distribuição dos atendimentos.')}<aside class="case-note reveal"><p class="mono accent">IDENTIFICAÇÃO PÚBLICA</p><h3>CPF identifica; não autentica.</h3><p>A consulta não revela nome, telefone nem histórico e não permite sobrescrever livremente um cadastro.</p></aside></div>`);
const ordinyPayments=section('pagamentos','paper',heading('05 / PAGAMENTOS','Duas relações financeiras.','A assinatura da plataforma e o pagamento do atendimento têm destinatários e responsabilidades próprios.')+`<div class="two-columns"><article class="payment-block reveal"><p class="mono">USO DO SAAS</p><h3>Estabelecimento → Ordiny</h3><p>A assinatura define recursos e limites do plano.</p></article><article class="payment-block reveal"><p class="mono">PAGAMENTO DO ATENDIMENTO</p><h3>Cliente → conta da unidade</h3><p>Conta Stripe da própria unidade, sem comissão da Ordiny.</p></article></div><div class="two-columns">${info('Checkout do provedor','O pagamento online é realizado no checkout do provedor, com os meios de pagamento disponíveis.')}${info('Responsabilidade da unidade','A unidade responde por taxas, reembolsos e contestações. Referências e histórico evitam registros duplicados.')}</div>`);
const ordinyChat=section('conversas','',heading('06 / CONVERSAS','Automatizar com limites claros.','Cada unidade usa seu próprio número do WhatsApp Business. O chatbot conduz o agendamento; lembretes e ações para retomar o contato com clientes têm controles próprios.')+`<div class="decision-grid"><div class="stack">${decision('DECISÃO / AUTOMAÇÃO','Devolver o controle a uma pessoa.','O cliente pode precisar de ajuda fora do roteiro.','Quando o cliente pede um atendente, o sistema avisa os operadores autorizados e pausa a automação da conversa. Desativar os lembretes mantém o chatbot ativo.','O atendimento humano termina manualmente ou após 30 minutos sem atividade do cliente.')}${info('Recuperação com consentimento','O recurso depende de contratação, consentimento do cliente, critérios de elegibilidade, intervalo entre contatos e um modelo de mensagem de marketing aprovado.')}${info('Mensagem aceita não significa mensagem entregue','Os registros distinguem aceitação pela Meta, entrega e falha.')}<aside class="case-note reveal"><p class="eyebrow accent">IA / EVOLUÇÃO DESATIVADA POR PADRÃO</p><h3>Interpretar a mensagem. Preservar a regra.</h3><p>A IA interpreta mensagens em linguagem natural e as encaminha para o fluxo existente. Preços, disponibilidade e confirmação continuam seguindo as regras do sistema.</p><p>As respostas da IA passam por validação. Há encaminhamento para atendimento humano e controles de acesso, orçamento, consumo e desativação.</p></aside></div><figure class="case-note chat-screen reveal"><p class="eyebrow accent">05 / CONTROLES DO WHATSAPP</p><div class="ordiny-phone whatsapp"><img src="assets/figma/o7-imgImage53.png" alt="Configuração do WhatsApp: conexão, lembretes, testes e templates" width="533" height="799" loading="lazy"></div><figcaption>Conexão, lembretes, testes e templates têm controles separados.</figcaption><p class="mono">TELA DE DESIGN / DADOS ILUSTRATIVOS</p></figure></div>`);
const ordinyArchitecture=section('construcao','paper',heading('07 / LEITURA COMPLEMENTAR','O que sustenta a experiência.','As escolhas de construção apoiam a consistência da interface e a confiabilidade das operações.')+`<div class="architecture-list">${[['INTERFACE','Consistência entre telas','React + TypeScript no Cloudflare Pages. Componentes compartilhados para desktop, mobile e PWA; temas de unidade e BackOffice separados.'],['REGRAS E COORDENAÇÃO','Reservas protegidas','Workers + Hono validam regras; D1 armazena dados; Durable Objects coordenam operações críticas.'],['TRABALHO EM SEGUNDO PLANO','Trabalho em segundo plano','Queues e tarefas agendadas processam atividades; R2 guarda imagens; KV apoia configurações.']].map(([label,title,body])=>`<article class="reveal"><div><p class="mono">${label}</p><h3>${title}</h3></div><p>${body}</p></article>`).join('')}</div><div class="two-columns">${info('O cache agiliza o retorno à agenda','As datas já consultadas são carregadas do cache e atualizadas em segundo plano. A confirmação continua verificando a disponibilidade atual.')}${info('Proteções ao longo da operação','Isolamento entre contas e unidades, permissões, validações, auditoria e verificação de webhooks.')}</div><p>Ações sensíveis pedem confirmação adicional; imagens são validadas e reprocessadas.</p>`);
const ordinyDelivery=section('entrega','paper',heading('08 / ENTREGA','Em desenvolvimento. Impacto a avaliar.','A jornada está implementada em ambiente de homologação. O projeto continua em desenvolvimento; os benefícios abaixo ainda precisam ser avaliados em uso real.')+`<p class="mono">OBJETIVOS DO PRODUTO / SEM RESULTADOS COMERCIAIS MENSURADOS</p><div class="two-columns">${info('Menos retrabalho','Reduzir registros repetidos entre conversa, reserva, atendimento e pagamento.')}${info('Uma operação mais clara','Tornar agenda, responsabilidades e relacionamento mais fáceis de acompanhar.')}</div><p>Próximo passo: observar clientes e operadores usando a jornada, concluir a homologação e medir o efeito na rotina.</p>${link(ordinyUrl,'Abrir a Ordiny ↗')}`);
page('ordiny.html','Ordiny: Estudo de caso','Da captação à gestão do atendimento: produto, UX/UI, desenvolvimento e decisões da plataforma Ordiny.',ordinyIntro+ordinyProduct+ordinyContext+ordinyJourney+ordinyOperations+ordinyBooking+ordinyPayments+ordinyChat+ordinyArchitecture+ordinyDelivery+section('','contact',heading('','Outros contextos.<br> Outras decisões.')+link('projetos.html','Explorar todos os projetos ↗','button button-dark')));
const cashBody=require('./cash-case.cjs')({section,heading,link,figure});
page('cash-advance.html','Cash Advance: Estudo de caso','Jornada financeira para motoristas: pesquisa, antecipação, Pix, cartão virtual, Caixinhas, crédito e sistema visual.',cashBody);
require('./art-copy.cjs').reviewSavedArt(root);
console.log('Páginas geradas: projetos.html, ordiny.html, cash-advance.html');
