const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname,'../assets/css');
const groups = {
  'site.css':['fonts.css','style.css','language.css','chibi-pet.css'],
  'home.css':['hero-motion.css','hero-glitch.css','hero-particles.css','hero-blueprint.css','skills-marquee.css']
};
function buildStyles() {
  for (const [output, sources] of Object.entries(groups)) {
    const css = sources.map(file => fs.readFileSync(path.join(root,file),'utf8').replace(/@import\s+url\(['"]?fonts\.css[^)]*\);/g,'')).join('\n');
    fs.writeFileSync(path.join(root,output),`/* Generated by scripts/build-styles.cjs. Edit the source stylesheets. */\n${css}`);
  }
}
module.exports = buildStyles;
if(require.main===module)buildStyles();
